[versions]
kotlin = "1.9.0"
compose = "1.4.3"
compose-compiler = "1.5.2"
koin = "3.4.3"
coroutines = "1.6.4"
navigation = "0.1.0"
android = "8.1.1"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.16.0" }
dependency-updates = { id = "com.github.ben-manes.versions", version = "0.47.0" }

[libraries]
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.6.0" }
navigation-screens-viewmodel = { module = "io.github.lukwol:navigation-screens-viewmodel", version.ref = "navigation" }
navigation-windows = { module = "io.github.lukwol:navigation-windows", version.ref = "navigation" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version = "1.0.4" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-android-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
compose-android-activity = { module = "androidx.activity:activity-compose", version = "1.7.2" }
compose-android-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-android-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-android-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-android-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-android-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }

